{
 "title": "BAUM FPlus",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(baumStatsNodeName,job)"
    }
   },
   {
    "name": "FCTarget",
    "query": {
     "query": "label_values({job=\"$job\"},baumStatsFCTarget)"
    }
   },
   {
    "name": "FCIndex",
    "query": {
     "query": "label_values({job=\"$job\", baumStatsFCTarget=\"$FCTarget\"},baumStatsFCIndex)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overall load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU load",
     "type": "timeseries",
     "description": "Overall CPU load by node",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "baumStatsNodeCPULoad{job=\"$job\"}/100",
       "legendFormat": "Node{{baumStatsNodeIndex}}"
      }
     ]
    },
    {
     "title": "RAM used",
     "type": "timeseries",
     "description": "Overall RAM used by node",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "baumStatsNodeUsedRam{job=\"$job\"}",
       "legendFormat": "Node {{baumStatsNodeIndex}} used RAM"
      },
      {
       "expr": "baumStatsNodeTotalRam{job=\"$job\"}",
       "legendFormat": "Node {{baumStatsNodeIndex}} total RAM"
      }
     ]
    },
    {
     "title": "Cache hit",
     "type": "timeseries",
     "description": "Cache hit in percent",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "baumStatsCommonCacheL1Hit{job=\"$job\"}",
       "legendFormat": "L1 Cahe Hit"
      },
      {
       "expr": "baumStatsCommonCacheL2Hit{job=\"$job\"}",
       "legendFormat": "L2 Cahe Hit"
      }
     ]
    },
    {
     "title": "Cache read/write",
     "type": "timeseries",
     "description": "Read/write back of cache",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "baumStatsCommonCacheReadBack{job=\"$job\"}",
       "legendFormat": "Cache Read Back"
      },
      {
       "expr": "baumStatsCommonCacheWriteBack{job=\"$job\"}",
       "legendFormat": "Cache Write Back"
      }
     ]
    }
   ]
  },
  {
   "title": "Ethernet load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ethernet Receiving/Transmitting Rate - Node 1",
     "type": "timeseries",
     "description": "Data receiving rate (b/s)",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "baumStatsNodeEthernetDataReceivingRate{baumStatsNodeIndex=\"1\", job=\"$job\"} * on (baumStatsNodeEthernetPortIndex) group_left(baumStatsNodeEthernetPortName) baumStatsNodeEthernetPortName{baumStatsNodeIndex=\"1\", job=\"$job\"}",
       "legendFormat": "{{baumStatsNodeEthernetPortName}} recv"
      },
      {
       "expr": "baumStatsNodeEthernetDataTransmittingRate{baumStatsNodeIndex=\"1\", job=\"$job\"} * on (baumStatsNodeEthernetPortIndex) group_left(baumStatsNodeEthernetPortName) baumStatsNodeEthernetPortName{baumStatsNodeIndex=\"1\", job=\"$job\"}",
       "legendFormat": "{{baumStatsNodeEthernetPortName}} trans"
      }
     ]
    },
    {
     "title": "Ethernet Receiving/Transmitting Rate - Node 2",
     "type": "timeseries",
     "description": "Data receiving rate (b/s)",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "baumStatsNodeEthernetDataReceivingRate{baumStatsNodeIndex=\"2\", job=\"$job\"} * on (baumStatsNodeEthernetPortIndex) group_left(baumStatsNodeEthernetPortName) baumStatsNodeEthernetPortName{baumStatsNodeIndex=\"2\", job=\"$job\"}",
       "legendFormat": "{{baumStatsNodeEthernetPortName}} recv"
      },
      {
       "expr": "baumStatsNodeEthernetDataTransmittingRate{baumStatsNodeIndex=\"2\", job=\"$job\"} * on (baumStatsNodeEthernetPortIndex) group_left(baumStatsNodeEthernetPortName) baumStatsNodeEthernetPortName{baumStatsNodeIndex=\"2\", job=\"$job\"}",
       "legendFormat": "{{baumStatsNodeEthernetPortName}} trans"
      }
     ]
    }
   ]
  },
  { "title": "Pools load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Pools read/write IOPS",
   "type": "timeseries",
   "description": "Read/write speed of pool (IO/s)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "baumStatsPoolsReadIOPS{job=\"$job\"} * on (baumStatsPoolsIndex) group_left(baumStatsPoolsName) baumStatsPoolsName{job=\"$job\"}",
     "legendFormat": "{{baumStatsPoolsName}} Read"
    },
    {
     "expr": "baumStatsPoolsWriteIOPS{job=\"$job\"} * on (baumStatsPoolsIndex) group_left(baumStatsPoolsName) baumStatsPoolsName{job=\"$job\"}",
     "legendFormat": "{{baumStatsPoolsName}} Write"
    }
   ]
  },
  {
   "title": "Pools read/write throughput",
   "type": "timeseries",
   "description": "Read/write speed of pool (B/s)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "baumStatsPoolsRead{job=\"$job\"} * on (baumStatsPoolsIndex) group_left(baumStatsPoolsName) baumStatsPoolsName{job=\"$job\"}",
     "legendFormat": "{{baumStatsPoolsName}} Read"
    },
    {
     "expr": "baumStatsPoolsWrite{job=\"$job\"} * on (baumStatsPoolsIndex) group_left(baumStatsPoolsName) baumStatsPoolsName{job=\"$job\"}",
     "legendFormat": "{{baumStatsPoolsName}} Write"
    }
   ]
  },
  { "title": "FC load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "FC read/write IOPS by targets",
   "type": "timeseries",
   "description": "Read/Write speed of FC (IO/s)",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "baumStatsFCReadIOPS{job=\"$job\"} * on (baumStatsFCIndex) group_left(baumStatsFCTarget) baumStatsFCTarget{job=\"$job\"}",
     "legendFormat": "{{ baumStatsFCTarget}} read"
    },
    {
     "expr": "baumStatsFCWriteIOPS{job=\"$job\"} * on (baumStatsFCIndex) group_left(baumStatsFCTarget) baumStatsFCTarget{job=\"$job\"}",
     "legendFormat": "{{baumStatsFCTarget}} write"
    }
   ]
  },
  {
   "title": "FC Target $FCTarget read/write IOPS by initiators",
   "type": "timeseries",
   "description": "Read/write speed initiator of FC (IO/s)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "baumStatsFCInitiatorReadIOPS{job=\"$job\", baumStatsFCIndex=\"$FCIndex\"} * on (baumStatsFCInitiatorIndex) group_left(baumStatsFCInitiatorName) baumStatsFCInitiatorName{job=\"$job\", baumStatsFCIndex=\"$FCIndex\"}",
     "legendFormat": "{{baumStatsFCInitiatorName}} read"
    },
    {
     "expr": "baumStatsFCInitiatorWriteIOPS{job=\"$job\", baumStatsFCIndex=\"$FCIndex\"} * on (baumStatsFCInitiatorIndex) group_left(baumStatsFCInitiatorName) baumStatsFCInitiatorName{job=\"$job\", baumStatsFCIndex=\"$FCIndex\"}",
     "legendFormat": "{{baumStatsFCInitiatorName}} write"
    }
   ]
  },
  {
   "title": "FC read/write throughput by targets",
   "type": "timeseries",
   "description": "Read/write speed of FC (B/s)",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "baumStatsFCRead{job=\"$job\"} * on (baumStatsFCIndex) group_left(baumStatsFCTarget) baumStatsFCTarget{job=\"$job\"}",
     "legendFormat": "{{baumStatsFCTarget}} read"
    },
    {
     "expr": "baumStatsFCWrite{job=\"$job\"} * on (baumStatsFCIndex) group_left(baumStatsFCTarget) baumStatsFCTarget{job=\"$job\"}",
     "legendFormat": "{{baumStatsFCTarget}} write"
    }
   ]
  },
  {
   "title": "FC Target $FCTarget read/write throughput by initiators",
   "type": "timeseries",
   "description": " Read/write speed initiator of FC (B/s)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "baumStatsFCInitiatorRead{job=\"$job\", baumStatsFCIndex=\"$FCIndex\"} * on (baumStatsFCInitiatorIndex) group_left(baumStatsFCInitiatorName) baumStatsFCInitiatorName{job=\"$job\", baumStatsFCIndex=\"$FCIndex\"}",
     "legendFormat": "{{baumStatsFCInitiatorName}} read"
    },
    {
     "expr": "baumStatsFCInitiatorWrite{job=\"$job\", baumStatsFCIndex=\"$FCIndex\"} * on (baumStatsFCInitiatorIndex) group_left(baumStatsFCInitiatorName) baumStatsFCInitiatorName{job=\"$job\", baumStatsFCIndex=\"$FCIndex\"}",
     "legendFormat": "{{baumStatsFCInitiatorName}} write"
    }
   ]
  }
 ]
}